---

# Handle boot and autologin settings
- name: enable cli only
  command: "raspi-config nonint do_boot_behaviour B1"
  when: not enable_gui and not enable_autologin and (raspi_gui_enabled or raspi_autologin_enabled)
  tags:
    - raspi

- name: enable cli with autologin
  command: "raspi-config nonint do_boot_behaviour B2"
  when: not enable_gui and enable_autologin and (raspi_gui_enabled or not raspi_autologin_enabled)
  tags:
    - raspi

- name: enable desktop gui
  command: "raspi-config nonint do_boot_behaviour B3"
  when: enable_gui and not enable_autologin and (not raspi_gui_enabled or raspi_autologin_enabled)
  tags:
    - raspi

- name: enable desktop gui with autologin
  command: "raspi-config nonint do_boot_behaviour B4"
  when: enable_gui and enable_autologin and (not raspi_gui_enabled or raspi_autologin_enabled)
  tags:
    - raspi

- name: set bootwait option
  command: "raspi-config nonint do_boot_wait {{ 0 if enable_bootwait else 1 }}"
  when: "enable_bootwait | default(false) and enable_bootwait != raspi_bootwait_enabled"
  tags:
    - raspi

- name: set boot splash option
  command: "raspi-config nonint do_boot_splash {{ 0 if enable_bootsplash else 1 }}"
  when: "enable_bootsplash | default(false) and enable_bootsplash != raspi_bootsplash_enabled"
  tags:
    - raspi

- name: enable/disable camera
  command: "raspi-config nonint do_camera {{ 0 if enable_camera else 1 }}"
  when: "enable_camera | default(false) and enable_camera != raspi_camera_enabled"
  tags:
    - raspi

- name: enable/disable VNC server
  command: "raspi-config nonint do_vnc {{ 0 if enable_vnc else 1 }}"
  when: "enable_vnc | default(false) and enable_vnc != raspi_vnc_enabled"
  tags:
    - raspi

- name: enable/disable SPI
  command: "raspi-config nonint do_spi {{ 0 if enable_spi else 1 }}"
  when: "enable_spi | default(false) and enable_spi != raspi_spi_enabled"
  tags:
    - raspi

- name: enable/disable I2C
  command: "raspi-config nonint do_i2c {{ 0 if enable_i2c else 1 }}"
  when: "enable_i2c | default(false) and enable_i2c != raspi_i2c_enabled"
  tags:
    - raspi

- name: enable/disable serial
  command: "raspi-config nonint do_serial {{ 0 if enable_serial else 1 }}"
  when: "enable_serial | default(false) and enable_serial != raspi_serial_enabled"
  tags:
    - raspi

- name: enable/disable hardware serial
  command: "raspi-config nonint do_serial_hw {{ 0 if enable_serial_hw else 1 }}"
  when: "enable_serial_hw | default(false) and enable_serial_hw != raspi_serial_hw_enabled"
  tags:
    - raspi

- name: enable/disable onewire
  command: "raspi-config nonint do_onewire {{ 0 if enable_onewire else 1 }}"
  when: "enable_onewire | default(false) and enable_onewire != raspi_onewire_enabled"
  tags:
    - raspi

- name: enable/disable remote GPIO
  command: "raspi-config nonint do_rgpio {{ 0 if enable_rgpio else 1 }}"
  when: "enable_rgpio | default(false) and enable_rgpio != raspi_rgpio_enabled"
  tags:
    - raspi

- name: enable/disable HDMI overscan
  command: "raspi-config nonint do_overscan {{ 0 if enable_overscan else 1 }}"
  when: "enable_overscan | default(false) and enable_overscan != raspi_overscan_enabled"
  tags:
    - raspi

- name: expand file system
  command: "raspi-config nonint do_expand_rootfs"
  when: raspi_fs_expandable
  tags:
    - raspi
