---
raspi_hostname: "clovermill"
raspi_domain: "local"
raspi_locale: "en_US.UTF-8"
raspi_timezone: "America/Los_Angeles"
xkblayout: "us"
wifi_country: "US"
enable_gui: False
enable_autologin: False
enable_bootwait: False
enable_bootsplash: False
enable_camera: True
enable_vnc: False
enable_spi: False
enable_i2c: False
enable_serial: False
enable_serial_hw: False
enable_onewire: False
enable_rgpio: False
darshan_dev: False
