---
### Hosts that must be present in /etc/hosts
etc_hosts_contents:
  - { name: 'clovermill',  ip: '192.168.1.149' }
  - { name: 'cloverfield', ip: '192.168.1.153' }
  - { name: 'clovermine',  ip: '192.168.1.154' }

### Users that must be present on the system
create_users:
  - name: glock
    comment: "Glenn K. Lockwood"
    uid: 1024
    group: users
    # don't include the group from 'group:' above in the 'groups:' below; this
    # breaks idempotency for some reason
    groups: "adm,dialout,sudo,audio,video,plugdev,games,input,netdev,spi,i2c,gpio"
    pubkey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCjx1Fevx4XODj8pJy/qRZDwQCRwNl0tJ3gWlDy1dB/AtdapVh5XYDUI99R+JqqzGgME9Bif6p1K6bqClLQh7MeY57L9IyjtqBF2t6/vNeKdOYDYQcBwL1p7vbGNTfKxYF2G4Lw+tRVGr3c+sCvA6r5UUAIhXNXTs7fLZanO6JGwITlJFcxDXPmITEhoXu4yTFqA0j1yp/K7I7dvmlhG/Yq+8P6zTJww1Zpy3aMaJ9gB4KR9jclW67wQZ3kVkFcyJtHXRI/LTzfAitB9W1X0svXysy88DiZsBGm1UmrUuFD3JPRn0SRRYchW5RdZ7MDPYWUDWweZIeuWvWRKzMkB5VJ"
